@base = http://localhost:3002/api

### includes favorite array
GET {{base}}/users/me HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDY5ZmFmNWIwNGY5ZjNiOWMzZmE0YzkiLCJwYWludGVyIjp0cnVlLCJpYXQiOjE2MTc1NTgyNjF9.lrbZOTelYbrQDvb4MJagaWNZzcFi1WYSD9iqKYtNpRU
### get drawing info from all users (for example favorites)
GET {{base}}/users/drawings?numbers=412066,128949,877558,858424 HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDY5ZmFmNWIwNGY5ZjNiOWMzZmE0YzkiLCJwYWludGVyIjp0cnVlLCJpYXQiOjE2MTc1NTgyNjF9.lrbZOTelYbrQDvb4MJagaWNZzcFi1WYSD9iqKYtNpRU
### add as painter
PATCH {{base}}/users/add-favorite HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDY5ZmFmNWIwNGY5ZjNiOWMzZmE0YzkiLCJwYWludGVyIjp0cnVlLCJpYXQiOjE2MTc1NTgyNjF9.lrbZOTelYbrQDvb4MJagaWNZzcFi1WYSD9iqKYtNpRU
Content-Type: application/json

{
    "favorites": ["412066"]
}
### delete as painter
PATCH {{base}}/users/delete-favorite HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDY5ZmFmNWIwNGY5ZjNiOWMzZmE0YzkiLCJwYWludGVyIjp0cnVlLCJpYXQiOjE2MTc1NTgyNjF9.lrbZOTelYbrQDvb4MJagaWNZzcFi1WYSD9iqKYtNpRU
Content-Type: application/json

{
    "favorites": ["412066"]
}
### add not as painter
PATCH {{base}}/users/add-favorite HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDY5ZmJkMmIwNGY5ZjNiOWMzZmFkZmMiLCJwYWludGVyIjpmYWxzZSwiaWF0IjoxNjE3NTU4NDkxfQ.k8JobvrQzdOkrx3Jb1qlp5-pF-ODpmHx2Kg01FDXzuc
Content-Type: application/json

{
    "favorites": ["412066"]
}
###
GET {{base}}/drawings/my-drawings HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDY5ZmFmNWIwNGY5ZjNiOWMzZmE0YzkiLCJwYWludGVyIjp0cnVlLCJpYXQiOjE2MTc1NTgyNjF9.lrbZOTelYbrQDvb4MJagaWNZzcFi1WYSD9iqKYtNpRU
###
POST {{base}}/drawings/6069fb03b04f9f3b9c3fa4ca HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDY5ZmFmNWIwNGY5ZjNiOWMzZmE0YzkiLCJwYWludGVyIjp0cnVlLCJpYXQiOjE2MTc1NTgyNjF9.lrbZOTelYbrQDvb4MJagaWNZzcFi1WYSD9iqKYtNpRU

